spring.application.name=classification-diabetes-ai

azure.openai.key=BZrL0RWv1php7klbvCY5W2owuCwjZBKr9j9RWxbptDJQUXE6O6QeJQQJ99BIACHYHv6XJ3w3AAAAACOGydqc 
azure.openai.endpoint=https://physi-mfopusfi-eastus2.services.ai.azure.com/
azure.openai.deployment=gpt-5-mini
